#!/bin/bash
#------------------------------------------------------------------------------#
#Title           :Aliases
#Author          :Ivan Batistic
#Date            :01/2023
#Version         :0.1
#Bash_version    :5.1.16(1)-release
#Description     :My collection of bash shell aliases
#------------------------------------------------------------------------------#


# Get rid of command not found
alias cd..='cd ..'
 
# Faster moving around
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'

# Calculator with math support
alias bc='bc -l'

# Live monitoring sensors output
alias temp='watch sensors'

# Changing bash PS1 prompt
alias bs='export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ "'
alias bss='export PS1="\[\033[01;34m\]\W\[\033[00m\] > "'
alias bbs='export PS1="\n\[\033[01;34m\][\w]\n\[\033[01;32m\] -> \[\033[00m\]"'
# Reset it back
alias br='export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "'

# Gnome-open is xdg-open on newer versions of ubuntu
alias gnome-open='xdg-open'

# Use color diff instead of diff
alias diff='colordiff'

# Active (open) TCP/UDP ports
alias ports='netstat -tulanp'

# Memory info
alias memInfo='free -m -l -t'

# Show memory demanding apps
alias psMemInfo='ps auxf | sort -nr -k 4 | head -10'

# Show cpu demanding apps
alias psCpuInfo='ps auxf | sort -nr -k 3 | head -10'

#------------------------------------------------------------------------------#
