#!/bin/bash
#------------------------------------------------------------------------------#
#Title           :Functions
#Author          :Ivan Batistic
#Date            :01/2023
#Version         :0.1
#Bash_version    :5.1.16(1)-release
#Description     :My collection of bash shell functions
#------------------------------------------------------------------------------#

# Function used to check number of arguments
# Arguments: number of arguments, required number of arguments
# Return: 1 if number of arguments not match required number
checkArgNum() {
    if [[ $1 -ne $2 ]]; then
        echo "$2 argument required, $1 provided" >&2
        return 1;
    fi
}

# Save working directory path, use wd to relocate terminal on it
# Arguments: None
# Outputs: Writes location to $HOME/.saved_dir
swd() {
    checkArgNum $# "0"
    returnValue=$?
    if [[ $returnValue -eq 1 ]]
    then
        return 1;
    fi

    cwd=$(pwd)

    echo $cwd > $HOME/.saved_dir

    echo "Saved current working dir: $cwd"
}


# Change to directory saved using swd() function
# Arguments: None
# Outputs: Change terminal location to location saved in $HOME/.saved_dir
wd() {
    checkArgNum $# "0"
    returnValue=$?
    if [[ $returnValue -eq 1 ]]
    then
        return 1;
    fi

    if [ -f $HOME/.saved_dir ]; then
        cwd=$(<$HOME/.saved_dir)
        cd $cwd
    fi
}

# See the most used commands in terminal
# Arguments: None
# Outputs: Prints most used commands
printComandsUsage () {
    checkArgNum $# "0"
    returnValue=$?
    if [[ $returnValue -eq 1 ]]
    then
        return 1;
    fi

    history|awk '{print $2}'|awk 'BEGIN {FS="|"} {print $1}'|sort|uniq -c|sort -rn
}

# Find file and grep expression through it
# Arguments: file name and expression
# Outputs: locations of expression for given file name
findGrep () {
    checkArgNum $# "2"
    returnValue=$?
    if [[ $returnValue -eq 1 ]]
    then
        return 1;
    fi

    find . -name "$1" | xargs -I {} grep -n --color "$2" {}
}

# Run emacs always in backgroud
# Globals: None
# Arguments: None
# Outputs: Run emacs & disown
emacs () {
  /usr/bin/emacs "$@" &
  disown;
}

# This makes it easier to separate normal status from actual issues.
# https://google.github.io/styleguide/shellguide.html
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
}

#------------------------------------------------------------------------------#
